### ISSUE TITLE
ImportError: No module named imutils.video

### ISSUE THREAD

**Issue by mrpmorris** [sniperdrone/blink_to_morse#1]
I keep getting an error "ImportError: No module named imutils.video" when I try to execute your code. I have updated imutils to the latest version but still it doesn't work. Can you offer any advice?

Thanks

(Terminal output)
deeplearning@deep-learning-virtual-machine:~/PycharmProjects/blink_to_morse$ pip install --upgrade imutils --no-cache-dir

Requirement already up-to-date: imutils in /usr/local/lib/python3.5/dist-packages

deeplearning@deep-learning-virtual-machine:~/PycharmProjects/blink_to_morse$ python detect_blinks.py --shape-predictor ./shape_predictor_68_face_landmarks.dat

Traceback (most recent call last):
  File "detect_blinks.py", line 9, in <module>
    from imutils.video import FileVideoStream
ImportError: No module named imutils.video

**Comment by fronay** [comment]
Hm, can't replicate on my machine (I'm using python 2.7, looks like you are using python 3?)
My guess is that there's a python 2/3 and hence pip/pip3 import problem, see the following similar-sounding issue:
https://github.com/jrosebr1/imutils/issues/24
Quoting: "It looks like you pip installed imutils using python2's pip and so that's why python3 can't import it. You might try: sudo pip3 install imutils"

Btw, if you're mainly interested in the blink detection itself, not the alphabet board or other add-ons, I'd check out Adrian Rosebrock's original blog post:
http://www.pyimagesearch.com/2017/04/24/eye-blink-detection-opencv-python-dlib/
where you can sign up to get the undoctored source code (I can also send it to you as a zip if needed).
As for the code here (ahem, "messy_main.py") the blog author told me he'd help me clean it up sometime this summer for a separate blog post.

**Comment by lillipu** [comment]
Hi I got the same error. 
I am using python 2.7. and used pipi install imutils. I can import imutils, but not imutils.video. Any suggestions?

Solved it with sudo pip2 install imutils! :)
